[directory]
format	= "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "ðŸŒ± "

[kubernetes]
disabled = false
format = '[$context \($namespace\)](green)'

[package]
disabled = true

[rust]
format = "$symbol"